---
apiVersion: "schemaregistry.jikkou.io/v1beta2"
kind: "SchemaRegistrySubject"
metadata:
  # The Schema Subject Name
  name: "Person"
  labels: { }
  annotations: { }
spec:
  compatibilityLevel: "FULL_TRANSITIVE"
  schemaType: "AVRO"
  schema: 
    # The path must be relative to the root folder of the Github repository.
    $ref: ./schemas/avro/Person.avsc

